modLoader = "javafml"
loaderVersion = "[37,)"
license = "¯\\_(ツ)_/¯"
[[mods]]
modId = "opmaak"
version = "${file.jarVersion}"
displayName = "Opmaak"
authors = "nierennakker & SudoQ"
description = '''
make your life more difficult
'''
[[dependencies.opmaak]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
side = "CLIENT"
[[dependencies.opmaak]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
side = "CLIENT"
