modLoader = "javafml"
loaderVersion = "[39,)"
license = "¯\\_(ツ)_/¯"
[[mods]]
modId = "opmaak"
version = "${file.jarVersion}"
displayName = "Opmaak"
authors = "nierennakker & SudoQ"
description = '''
make your life not worth it
'''
[[dependencies.opmaak]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
side = "CLIENT"
[[dependencies.opmaak]]
modId = "minecraft"
mandatory = true
versionRange="[1.18.1,1.19)"
side = "CLIENT"
