modLoader = "javafml"
loaderVersion = "[44,)"
license = "¯\\_(ツ)_/¯"
[[mods]]
modId = "opmaak"
version = "${file.jarVersion}"
displayName = "Opmaak"
authors = "nierennakker & SudoQ"
displayTest = "IGNORE_ALL_VERSION"
description = '''
make your life not worth it
'''
[[dependencies.opmaak]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
side = "CLIENT"
[[dependencies.opmaak]]
modId = "minecraft"
mandatory = true
versionRange="[1.19,1.20)"
side = "CLIENT"
